// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by remote_config_codegen.

import 'package:freezed_annotation/freezed_annotation.dart';

part 'remote_config_models.freezed.dart';
part 'remote_config_models.g.dart';

@freezed
abstract class Banner with _$Banner {
  const factory Banner({required String title, String? subtitle}) = _Banner;

  factory Banner.fromJson(Map<String, dynamic> json) => _$BannerFromJson(json);
}
