// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by remote_config_codegen.

import 'package:json_annotation/json_annotation.dart';

part 'remote_config_models.g.dart';

@JsonSerializable()
class Banner {
  const Banner({required this.title, this.subtitle});

  factory Banner.fromJson(Map<String, dynamic> json) => _$BannerFromJson(json);

  Map<String, dynamic> toJson() => _$BannerToJson(this);

  final String title;
  final String? subtitle;
}
