/// The header added to every generated Dart file.
///
/// It makes the ownership of generated output explicit and matches the common
/// convention used by Dart code-generation packages.
const String generatedCodeHeader =
    '// GENERATED CODE - DO NOT MODIFY BY HAND\n'
    '// Generated by remote_config_codegen.\n\n';
