import 'package:meta/meta.dart';

import 'dart_literal.dart';
import 'dart_model_registry.dart';
import 'dart_names.dart';
import 'dart_serializer.dart';
import 'dart_type_resolver.dart';
import 'constants.dart';
import 'json_schema.dart';

/// Defines how a serializer-specific Dart model file is rendered.
///
/// Implementations consume shared schema-derived model declarations while
/// owning imports, annotations, and model syntax for one serializer ecosystem.
abstract class DartModelRenderer {
  /// Creates a renderer base with shared serializer-independent behavior.
  const DartModelRenderer();

  /// Renders every registered model using [registry] and [resolver].
  ///
  /// The returned source includes [generatedCodeHeader] and is ready to be
  /// written as `remote_config_models.dart`.
  String render(DartModelRegistry registry, DartTypeResolver resolver);

  /// Selects the renderer that implements [serializer]'s source conventions.
  ///
  /// Keeping this dispatch point here means new serializers add one renderer
  /// rather than branching throughout the rest of the generator.
  static DartModelRenderer forSerializer(DartSerializer serializer) =>
      switch (serializer) {
        DartSerializer.jsonSerializable =>
          const JsonSerializableModelRenderer(),
        DartSerializer.freezed => const FreezedModelRenderer(),
      };

  /// Appends a Dart enum for the string enum values declared by [node].
  ///
  /// JSON enum literals are preserved through `@JsonValue` when their Dart
  /// field name differs. The initial generator intentionally rejects non-string
  /// enums because the supported Dart serializers require a string mapping.
  @protected
  void renderEnum(StringBuffer buffer, String enumName, JsonSchemaNode node) {
    if (node.enumValues.any((Object? value) => value is! String)) {
      throw FormatException(
        '$enumName enum values must all be strings in the first release.',
      );
    }
    buffer.writeln('enum $enumName {');
    for (final value in node.enumValues) {
      final serializedValue = value! as String;
      final valueName = DartNames.field(serializedValue);
      if (valueName != serializedValue) {
        buffer.writeln(
          "  @JsonValue('${DartLiteral.string(serializedValue)}')",
        );
      }
      buffer.writeln('  $valueName,');
    }
    buffer
      ..writeln('}')
      ..writeln();
  }
}

/// Renders JSON models annotated for `json_serializable`.
///
/// Output classes expose `fromJson` and `toJson` methods backed by the part
/// file generated by `json_serializable`.
class JsonSerializableModelRenderer extends DartModelRenderer {
  /// Creates a stateless `json_serializable` renderer.
  const JsonSerializableModelRenderer();

  @override
  String render(DartModelRegistry registry, DartTypeResolver resolver) {
    final buffer = StringBuffer(generatedCodeHeader)
      ..writeln("import 'package:json_annotation/json_annotation.dart';")
      ..writeln()
      ..writeln("part 'remote_config_models.g.dart';")
      ..writeln();

    for (final declaration in registry.declarations) {
      if (declaration.node.type == JsonSchemaType.object) {
        _renderObject(buffer, declaration.name, declaration.node, resolver);
      } else if (declaration.node.enumValues.isNotEmpty) {
        renderEnum(buffer, declaration.name, declaration.node);
      }
    }
    return buffer.toString();
  }

  void _renderObject(
    StringBuffer buffer,
    String className,
    JsonSchemaNode node,
    DartTypeResolver resolver,
  ) {
    buffer
      ..writeln('@JsonSerializable()')
      ..writeln('class $className {');
    final parameters = node.properties.entries
        .map(
          (entry) =>
              '${node.requiredProperties.contains(entry.key) ? 'required ' : ''}this.${DartNames.field(entry.key)}',
        )
        .join(', ');
    buffer.writeln('  const $className({$parameters});');
    buffer
      ..writeln()
      ..writeln(
        '  factory $className.fromJson(Map<String, dynamic> json) => _\$${className}FromJson(json);',
      )
      ..writeln()
      ..writeln(
        '  Map<String, dynamic> toJson() => _\$${className}ToJson(this);',
      )
      ..writeln();
    for (final entry in node.properties.entries) {
      final fieldName = DartNames.field(entry.key);
      if (fieldName != entry.key) {
        buffer.writeln("  @JsonKey(name: '${DartLiteral.string(entry.key)}')");
      }
      var fieldType = resolver.typeFor(entry.value);
      if (!node.requiredProperties.contains(entry.key) &&
          !fieldType.endsWith('?')) {
        fieldType = '$fieldType?';
      }
      buffer.writeln('  final $fieldType $fieldName;');
    }
    buffer
      ..writeln('}')
      ..writeln();
  }
}

/// Renders immutable JSON models using Freezed 3 syntax.
///
/// The emitted abstract classes and factory constructors are compatible with
/// the Freezed 3 configuration currently supported by this package.
class FreezedModelRenderer extends DartModelRenderer {
  /// Creates a stateless Freezed 3 renderer.
  const FreezedModelRenderer();

  // TODO(keigomichi): Add a renderer option only when Freezed 2 compatibility is needed.
  @override
  String render(DartModelRegistry registry, DartTypeResolver resolver) {
    final buffer = StringBuffer(generatedCodeHeader)
      ..writeln("import 'package:freezed_annotation/freezed_annotation.dart';")
      ..writeln()
      ..writeln("part 'remote_config_models.freezed.dart';")
      ..writeln("part 'remote_config_models.g.dart';")
      ..writeln();
    for (final declaration in registry.declarations) {
      if (declaration.node.type == JsonSchemaType.object) {
        _renderObject(buffer, declaration.name, declaration.node, resolver);
      } else if (declaration.node.enumValues.isNotEmpty) {
        renderEnum(buffer, declaration.name, declaration.node);
      }
    }
    return buffer.toString();
  }

  void _renderObject(
    StringBuffer buffer,
    String className,
    JsonSchemaNode node,
    DartTypeResolver resolver,
  ) {
    buffer
      ..writeln('@freezed')
      ..writeln('abstract class $className with _\$$className {');
    final parameters = node.properties.entries
        .map((entry) {
          final fieldName = DartNames.field(entry.key);
          var fieldType = resolver.typeFor(entry.value);
          final isRequired = node.requiredProperties.contains(entry.key);
          if (!isRequired && !fieldType.endsWith('?'))
            fieldType = '$fieldType?';
          final jsonKey = fieldName == entry.key
              ? ''
              : "@JsonKey(name: '${DartLiteral.string(entry.key)}') ";
          return '$jsonKey${isRequired ? 'required ' : ''}$fieldType $fieldName';
        })
        .join(', ');
    buffer
      ..writeln('  const factory $className({$parameters}) = _$className;')
      ..writeln()
      ..writeln(
        '  factory $className.fromJson(Map<String, dynamic> json) => '
        '_\$${className}FromJson(json);',
      )
      ..writeln('}')
      ..writeln();
  }
}
