name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1 # v1.8.0
        with:
          sdk: stable
      - run: dart pub upgrade --no-example
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze --fatal-infos lib bin test

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - sdk: 3.11.0
            dependencies: downgrade
          - sdk: stable
            dependencies: upgrade
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1 # v1.8.0
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub ${{ matrix.dependencies }} --no-example
      - run: dart analyze --fatal-infos lib bin test
      - run: dart test

  publish_dry_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1 # v1.8.0
        with:
          sdk: stable
      - run: dart pub publish --dry-run
